name: Bench
on:
  pull_request:
    types: [labeled]

permissions:
  deployments: write
  contents: write

jobs:
  bench_between_main_and_pr:
    if: ${{ github.event.label.name == 'run-benchmarks' }}
    name: Bench
    runs-on: ubuntu-latest
    steps:
      - name: Setup nightly toolchain
        run: |
          rustup set profile minimal
          rustup override set nightly
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Run benchmark on PR
        run: cargo bench | tee output.txt
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@52576c92bccf6ac60c8223ec7eb2565637cae9ba # v1.22.1
        with:
          tool: 'cargo'
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-always: true
          comment-on-alert: true
          alert-threshold: '150%'
          fail-on-alert: true
