name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  zizmor:
    name: zizmor
    permissions:
      actions: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
        with:
          advanced-security: false
          annotations: true
          version: 1.25.2

  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # MSRV and nightly
        version: [1.85.0, stable, nightly]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set toolchain
        run: |
          rustup set profile minimal
          rustup override set ${{ matrix.version }}

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Rustfmt check
        if: matrix.version == '1.85.0'
        run: |
          rustup component add rustfmt
          cargo fmt --all -- --check

      - name: Run `cargo test` on workspace
        if: matrix.version != '1.85.0'
        run: cargo test --workspace --exclude=phf_codegen_test --exclude=phf_macros_no_macros_test

      - name: phf_macros test without phf/macros
        if: matrix.version != '1.85.0'
        run: cargo test -p phf_macros_no_macros_test

      - name: phf_macros ptrhash test without phf/macros
        if: matrix.version != '1.85.0'
        run: cargo test -p phf_macros_no_macros_test --features ptrhash

      - name: phf_codegen test
        if: matrix.version != '1.85.0'
        run: cargo test -p phf_codegen_test

      - name: trybuild test
        if: matrix.version == 'stable'
        run: cargo test -p phf_macros_test -- --ignored

      - name: no_std build check
        working-directory: phf
        run: cargo build --no-default-features

      - name: all features check
        run: cargo check --workspace --all-features

      - name: unicase + macros features check
        run: cargo check -p unicase-example

      - name: deny check
        if: matrix.version == 'stable'
        uses: EmbarkStudios/cargo-deny-action@bb137d7af7e4fb67e5f82a49c4fce4fad40782fe # v2.0.20
